--Execution Plan
--Roadmap generated by a database on how it will execute your query step by step

--This exercise we will be using adventure works database
--Creating a heap table
SELECT *
INTO FactResellerSales_HP
FROM FactResellerSales

SELECT *
FROM FactResellerSales_HP

--there is a button next to tick mark
--Estimated Execution Plan
--predicts the execution plan without actually running the query

--same row another one
--Actual Execution Plan
--Shows the execution plan as it occured after running the query

--Live Execution Plan
--Shows the real-time execution flow as the query runs.

--Estimated vs Actual Plans
--If the prediction don't match the Actual Execution Plan, this indicate issues like inaccurate
--statistics or outdated indexes, leading to poor performance.

SELECT *
FROM FactResellerSales_HP

--Table Scan
--Reads the entire table page by page and row by row "everything"
--which can lead to slower query performance on larger tables


SELECT *
FROM FactResellerSales

--Index Scan
--Scans all data in an index to find matching rows

SELECT *
FROM FactResellerSales
ORDER BY SalesOrderNumber

SELECT *
FROM FactResellerSales_HP
ORDER BY SalesOrderNumber

SELECT * 
FROM FactResellerSales
WHERE CarrierTrackingNumber = '4911-403C-98'

CREATE NONCLUSTERED INDEX idx_FactReseller_CTA
ON FactResellerSales (CarrierTrackingNumber)

--Index Seek
--A targeted search within an index retrieving only specific rows
--Remeber execution plan has to be read from right to left

--Join Algorithms
--These are used in the backend of the database not like joins we write in query

--Nested Loops: Compares tables row by row; best for small tables
--Hash Match: Matches rows using a hash table; best for large tables
--Merge Join: Merge two sorted tables; efficient when both are sorted

SELECT
	p.EnglishProductName AS ProductName,
	SUM(s.SalesAmount) AS TotalSales
FROM FactResellerSales s
JOIN DimProduct p
ON p.ProductKey = s.ProductKey
GROUP BY p.EnglishProductName

--Converting to columnstore index
CREATE CLUSTERED COLUMNSTORE INDEX idx_FactResellerSalesHP
ON FactResellerSales_HP

SELECT
	p.EnglishProductName AS ProductName,
	SUM(s.SalesAmount) AS TotalSales
FROM FactResellerSales_HP s
JOIN DimProduct p
ON p.ProductKey = s.ProductKey
GROUP BY p.EnglishProductName

--SQL HINTS
--Commands you add to a query to force the database to run it
--in a specific way for better performance

SELECT --this query execution plan uses nested loop for join operation
	o.Sales,
	c.Country
FROM Sales.Orders o
LEFT JOIN Sales.Customers c
ON o.CustomerID = c.CustomerID

--Overwriting the execution to use Hash Join
SELECT 
	o.Sales,
	c.Country
FROM Sales.Orders o
LEFT JOIN Sales.Customers c
ON o.CustomerID = c.CustomerID 
OPTION (HASH JOIN) --Telling SQL to use Hash Join instead of Nested Loops

--Overwriting the execution plan to use Index Seek
SELECT 
	o.Sales,
	c.Country
FROM Sales.Orders o
LEFT JOIN Sales.Customers c WITH (FORCESEEK) --telling SQL to use Index Seek instead of Index Scan
ON o.CustomerID = c.CustomerID 
--OPTION (HASH JOIN)

--Overwriting the execution plan to use Specific Index
SELECT 
	o.Sales,
	c.Country
FROM Sales.Orders o
LEFT JOIN Sales.Customers c WITH (INDEX([PK_customers])) --telling SQL to use Index Seek instead of Index Scan
ON o.CustomerID = c.CustomerID 
--OPTION (HASH JOIN)
